version: '3'

services:
  db:
    image: postgres
  web:
    build: .
    command: bash -c "python manage.py makemigrations && python manage.py migrate"
    command: bash -c "python manage.py test"
    command: bash -c "python manage.py runserver 0.0.0.0:8000"
    volumes:
      - .:/fibonaci_volume
    ports:
      - "8000:8000"
    depends_on:
      - db