version: '3'

services:
  db:
    image: postgres
  web:
    build: .
    image: ramanado/fibonaci_api_web
    command: bash entrypoint.sh
    volumes:
      - .:/fibonaci_volume
    ports:
      - "8000:8000"
    depends_on:
      - db