apiVersion: apps/v1
kind: Deployment
metadata:
  name: fibonaci-api-deployment
spec:
  replicas: 3
  selector:
    matchLabels:
      app: fibonaci-api-web
  template:
    metadata:
      labels:
        app: fibonaci-api-web
    spec:
      containers:
      - name: fibonaciweb
        image: ramanado/fibonaci_api_web
        command: ["bash", "entrypoint.sh"]
        ports:
        - containerPort: 8000
        livenessProbe:
          httpGet:
            path: /
            port: 8000
          initialDelaySeconds: 15
          timeoutSeconds: 1
          periodSeconds: 10
        resources:
          requests:
            cpu: 200m

---

apiVersion: v1
kind: Service
metadata:
  name: fibonaci-svc
spec:
  type: NodePort
  selector:
    app: fibonaci-api-web
  ports:
  - protocol: TCP
    port: 8000
    targetPort: 8000