kind: Service
apiVersion: v1
metadata:
  name: fibonacci-api-canary
spec:
  type: NodePort
  selector:
    app: fibonacci-api
    track: canary
  ports:
  - protocol: TCP
    port: 8000
    nodePort: 8081

---

apiVersion: v1
kind: Deployment
metadata:
  name: fibonacci-api-deployment-canary
  labels:
    app: fibonacci-api
spec:
  replicas: $CANARY_REPLICAS
  selector:
    matchLabels:
      app: fibonacci-api
      track: canary
  template:
    metadata:
      labels:
        app: fibonacci-api
        track: canary
    spec:
      containers:
      - name: fibonacci-api
        image: $DOCKER_IMAGE_NAME:$BUILD_NUMBER
        ports:
        - containerPort: 8000
        livenessProbe:
          httpGet:
            path: ''
            port: 8000
          initialDelaySeconds: 15
          timeoutSeconds: 1
          periodSeconds: 10
        resources:
          requests:
            cpu: 200m